---
- hosts: all
  vars:
   User1: ""
  become: yes
  tasks:

   - name: Install the HTTPD on the other node.
     yum:
      name: httpd 
      state: present

     notify:
      - HTTP Restart


   - name: configure the httpd service with index.html  populated with facts and variables
     shell: 
       echo " Welcome to the web page of {{ ansible_hostname }} having ip address of {{ ansible_all_ipv4_addresses }} /n " > /var/www/html/index.html
       echo " This Page is Owned by {{ User1 }} " >> /var/www/html/index.html
      
   - name: bounce the httpd services
     service:
       name: httpd
       state: started

  handlers:
   - name: HTTP Restart
     service:
       name: httpd
       state: restarted



