---

- name: Ignore Error Playbook
  hosts: all
  become: yes
  tasks:

   - name: This will not be counted as failure
     command: /bin/date 1 2
     ignore_errors: yes

   - name: Second Task
     service: name=ntpd state=restarted
